# Generated by Django 3.0.5 on 2021-04-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('updated', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('countryInfo', models.CharField(max_length=150)),
                ('cases', models.CharField(max_length=100)),
                ('todayCases', models.CharField(max_length=100)),
                ('deaths', models.CharField(max_length=100)),
                ('todayDeaths', models.CharField(max_length=100)),
                ('recovered', models.CharField(max_length=100)),
                ('todayRecovered', models.CharField(max_length=100)),
                ('active', models.CharField(max_length=100)),
                ('critical', models.CharField(max_length=100)),
                ('casesPerOneMillion', models.CharField(max_length=100)),
                ('deathsPerOneMillion', models.CharField(max_length=100)),
                ('tests', models.CharField(max_length=100)),
                ('testsPerOneMillion', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('oneCasePerPeople', models.CharField(max_length=100)),
                ('oneDeathPerPeople', models.CharField(max_length=100)),
                ('activePerOneMillion', models.CharField(max_length=100)),
                ('recoveredPerOneMillion', models.CharField(max_length=100)),
                ('criticalPerOneMillion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'api_covid_data',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.CharField(max_length=100)),
                ('Country', models.CharField(db_column='Country,Other', default='country', max_length=100, primary_key=True, serialize=False)),
                ('TotalCases', models.CharField(db_column='TotalCases', default='cases', max_length=100)),
                ('New_cases', models.CharField(db_column='NewCases', default='new cases', max_length=100)),
                ('total_Deaths', models.CharField(db_column='TotalDeaths', default='total deaths', max_length=100)),
                ('new_deaths', models.CharField(db_column='NewDeaths', default='new deaths', max_length=100)),
                ('total_recovered', models.CharField(db_column='TotalRecovered', default='total recovered', max_length=100)),
                ('new_recovered', models.CharField(db_column='NewRecovered', default='new recovered', max_length=100)),
                ('active_cases', models.CharField(db_column='ActiveCases', default='active cases', max_length=100)),
                ('serious', models.CharField(db_column='Serious,Critical', default='serious cases', max_length=100)),
                ('total_cases_percent', models.CharField(db_column='Tot Cases/1M pop', default='total case/1M pop', max_length=100)),
                ('deaths_percent', models.CharField(db_column='Deaths/1M pop', default='deaths/1M pop', max_length=100)),
                ('total_tests', models.CharField(db_column='TotalTests', default='total tests', max_length=100)),
                ('tests_percent', models.CharField(db_column='Tests/ 1M pop', default='tests/1M pop', max_length=100)),
                ('population', models.CharField(db_column='Population', default='population', max_length=100)),
                ('continent', models.CharField(db_column='Continent', default='continent', max_length=100)),
                ('CaseEveryXppl', models.CharField(db_column='1 Caseevery X ppl', default='CaseEveryXppl', max_length=100)),
                ('DeathEveryXppl', models.CharField(db_column='1 Deathevery X ppl', default='DeathEveryXppl', max_length=100)),
                ('TesteveryXppl', models.CharField(db_column='1 Testevery X ppl', default='TesteveryXppl', max_length=100)),
            ],
            options={
                'db_table': 'web_crawler',
            },
        ),
    ]
