# Generated by Django 3.0.5 on 2021-04-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Covid',
        ),
    ]
