# Generated by Django 3.0.5 on 2021-04-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='task',
        ),
        migrations.AddField(
            model_name='todo',
            name='active_cases',
            field=models.CharField(default='active cases', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='country',
            field=models.CharField(default='country', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='deaths_percent',
            field=models.CharField(default='deaths/1M pop', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='new_cases',
            field=models.CharField(default='new cases', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='new_deaths',
            field=models.CharField(default='new deaths', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='population',
            field=models.CharField(default='population', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='serious',
            field=models.CharField(default='serious cases', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='tests_percent',
            field=models.CharField(default='tests/1M pop', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='total_Deaths',
            field=models.CharField(default='total deaths', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='total_cases',
            field=models.CharField(default='cases', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='total_cases_percent',
            field=models.CharField(default='total case/1M pop', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='total_recovered',
            field=models.CharField(default='total recovered', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='total_tests',
            field=models.CharField(default='total tests', max_length=100),
        ),
    ]
