# Generated by Django 3.0.5 on 2021-04-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210414_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='new_cases',
            new_name='New_cases',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='total_cases',
            new_name='TotalCases',
        ),
        migrations.AddField(
            model_name='todo',
            name='CaseEveryXppl',
            field=models.CharField(default='population', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='DeathEveryXppl',
            field=models.CharField(default='population', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='TesteveryXppl',
            field=models.CharField(default='population', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='continent',
            field=models.CharField(default='continent', max_length=100),
        ),
        migrations.AlterModelTable(
            name='todo',
            table='web_crawler',
        ),
    ]
